---
sudo: false
language: node_js
node_js:
  - '8'
cache:
  yarn: true
  directories:
    - node_modules

script:
  - lerna bootstrap
  - yarn run lint
  - yarn run test
  # - lerna run build
  - lerna run deploy
