---
sudo: false
language: node_js
node_js:
  - '8'
cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - yarn config set workspaces-experimental true

script:
  - lerna bootstrap
  - lerna run symlink
  - lerna run lint
  - yarn run test
  - lerna run build

deploy:
  provider: script
  script: lerna run deploy
  on:
    branch: master
