---
sudo: false
language: node_js
node_js:
  - '8'
cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.5.1
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn config set workspaces-experimental true

script:
  - lerna bootstrap
  - lerna run symlink
  - lerna run lint
  - yarn run test
  - lerna run build

  - cd $TRAVIS_BUILD_DIR
  - chmod +x ./deploy.sh

deploy:
  provider: script
  script: ./deploy.sh
  on:
    branch: master
