---
service: sidneyw-email

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  memorySize: 512

plugins:
  - serverless-offline

package:
  exclude:
    - "**/__test__/**/*"

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get

  signup:
    handler: index.signup
    events:
      - http:
          path: /signup
          method: post
          cors: true
    environment:
      MAILCHIMP_LIST: ${env:MAILCHIMP_LIST}
      MAILCHIMP_USER: ${env:MAILCHIMP_USER}
      MAILCHIMP_PASS: ${env:MAILCHIMP_PASS}

  contact:
    handler: index.contact
    events:
      - http:
          path: /contact
          method: post
          cors: true
    environment:
      AWS_SES_SENDER: ${env:AWS_SES_SENDER}
      AWS_SES_RECIPIENT: ${env:AWS_SES_RECIPIENT}
